lansweeper:
  hosts:
    ch-lansweeper1:
    ch-lansweeper2:
    lansweeper-app:
    lansweeper-scan:
    ne-lansweeper:
    ti-lansweeper:
    ti-lansweeper2:
    wj-lansweeper1:
    wj-lansweeper2:
  vars:
    ansible_user: "username@domain"
    ansible_password: "domain password"
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    update_categories: ['Application', 'Connectors', 'Critical Updates', 'Definition Updates', 'Developer Kits', 'Feature Packs', 'Guidance', 'Security Updates', 'Service Packs', 'Tools', 'Update Rollups', 'Updates']
    update_server_selection: windows_update
    package_url: http://172.28.7.35/
    package_name: LansweeperSetup.exe